apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: homer

configurations:
- kustomizeconfig.yaml

namespace: simpsons


vars:
- name: SERVICE_NAME
  objref:
    kind: Service
    name: service
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- route.yaml