apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: homer
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: homer-service
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect